name: Lazy trees performance comparison

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run-comparison:
    runs-on: ${{ matrix.examples.runner }}
    name: Evaluate the ${{ matrix.examples.package }} package on ${{ matrix.examples.runner }}
    permissions:
      id-token: write
      contents: read
    env:
      PKG: ${{ matrix.examples.package }}
    strategy:
      matrix:
        examples:
          - { runner: ubuntu-latest, package: cowsay }
          - { runner: macos-latest, package: cowsay }
          - { runner: ubuntu-latest, package: apacheKafka }
          - { runner: macos-latest, package: apacheKafka }
          - { runner: ubuntu-latest, package: firefox }
          - { runner: macos-latest, package: firefox }
          - { runner: ubuntu-latest, package: haskellPackages }
          - { runner: macos-latest, package: haskellPackages }
          - { runner: ubuntu-latest, package: pythonPackages }
          - { runner: macos-latest, package: pythonPackages }
    steps:
      - name: Fetch Nixpkgs
        uses: actions/checkout@v4
        with:
          repository: NixOS/nixpkgs
          ref: 2f2c8b33a3dc4bf9a3db1648d734fa8c64f9166b

      - name: Install Determinate Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true

      - name: Evaluate ${{ env.PKG }} without lazy trees
        run: |
          time nix eval --quiet .#${{ env.PKG }}

      - name: Evaluate ${{ env.PKG }} with lazy trees
        run: |
          # Turn on lazy trees
          sudo touch /etc/nix/nix.custom.conf
          echo "lazy-trees = true" | sudo tee -a /etc/nix/nix.custom.conf

          # Meaningless change
          echo "" >> flake.nix

          time nix eval --quiet .#${{ env.PKG }}
